import getGinghamChevronContinuumStripePositions from './getGinghamChevronContinuumStripePositions'
import realignTileColorIndicesToMaintainGinghamChevronContinuumAcrossGrid from './realignTileColorIndicesToMaintainGinghamChevronContinuumAcrossGrid'

export default {
	getGinghamChevronContinuumStripePositions,
	realignTileColorIndicesToMaintainGinghamChevronContinuumAcrossGrid,
}
